[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Card:set_cost
[[patches]]
[patches.pattern]
target = 'card.lua'
position = 'after'
pattern = "self.sell_cost = math.max(1, math.floor(self.cost/2)) + (self.ability.extra_value or 0)"
payload = '''
if self.ability and self.ability["hp_jtem_stats"] then
    local wits = self.ability["hp_jtem_stats"].wits or 0
    if to_number(wits) > 150 then
        self.sell_cost = self.sell_cost + math.max(1, math.floor(self.cost/2)) * (1 + (wits - 150) / 50)
    end
end
'''
match_indent = true
