[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
position = 'at'
pattern = '''
    if G.GAME.dollars >= 5 and not G.GAME.modifiers.no_interest then
        add_round_eval_row({bonus = true, name='interest', pitch = pitch, dollars = G.GAME.interest_amount*math.min(math.floor(G.GAME.dollars/5), G.GAME.interest_cap/5)})
'''
payload = '''
if G.GAME.dollars >= 5 and not G.GAME.modifiers.no_interest or G.GAME.modifiers.interest_to_budget then
  if G.GAME.modifiers.interest_to_budget then
   if G.GAME.modifiers.hands_to_budget then
      if G.GAME.dollars >= 5 then
        add_round_eval_credits({name='credits', pitch = pitch, credits = ((G.GAME.interest_amount*math.min(math.floor(G.GAME.dollars/5), G.GAME.interest_cap/5)) * 2) + G.GAME.current_round.hands_left*(G.GAME.modifiers.money_per_hand or 1)})
        credits = credits + ((G.GAME.interest_amount*math.min(math.floor(G.GAME.dollars/5), G.GAME.interest_cap/5)) * 2) + G.GAME.current_round.hands_left*(G.GAME.modifiers.money_per_hand or 1)
      else
        add_round_eval_credits({name='credits', pitch = pitch, credits = G.GAME.current_round.hands_left*(G.GAME.modifiers.money_per_hand or 1)})
        credts = credits + G.GAME.current_round.hands_left*(G.GAME.modifiers.money_per_hand or 1)
      end
   else
      add_round_eval_credits({name='credits', pitch = pitch, credits = ((G.GAME.interest_amount*math.min(math.floor(G.GAME.dollars/5), G.GAME.interest_cap/5)) * 2)})
      credits = credits + ((G.GAME.interest_amount*math.min(math.floor(G.GAME.dollars/5), G.GAME.interest_cap/5)) * 2)
   end
  else
      add_round_eval_row({bonus = true, name='interest', pitch = pitch, dollars = G.GAME.interest_amount*math.min(math.floor(G.GAME.dollars/5), G.GAME.interest_cap/5)})
  end

'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
position = 'at'
pattern = '''
dollars = dollars + G.GAME.interest_amount*math.min(math.floor(G.GAME.dollars/5), G.GAME.interest_cap/5)
'''
payload = '''
if not G.GAME.modifiers.interest_to_budget then
  dollars = dollars + G.GAME.interest_amount*math.min(math.floor(G.GAME.dollars/5), G.GAME.interest_cap/5)
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
position = 'at'
pattern = '''
        add_round_eval_row({dollars = G.GAME.current_round.hands_left*(G.GAME.modifiers.money_per_hand or 1), disp = G.GAME.current_round.hands_left, bonus = true, name='hands', pitch = pitch})
        pitch = pitch + 0.06
        dollars = dollars + G.GAME.current_round.hands_left*(G.GAME.modifiers.money_per_hand or 1)
'''
payload = '''
  if not G.GAME.modifiers.hands_to_budget then
        add_round_eval_row({dollars = G.GAME.current_round.hands_left*(G.GAME.modifiers.money_per_hand or 1), disp = G.GAME.current_round.hands_left, bonus = true, name='hands', pitch = pitch})
        pitch = pitch + 0.06
        dollars = dollars + G.GAME.current_round.hands_left*(G.GAME.modifiers.money_per_hand or 1)
  end
'''
match_indent = true


